# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 11:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20160229_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
                ('method', models.CharField(choices=[('get', 'get'), ('post', 'post')], max_length=10)),
                ('res_status', models.CharField(choices=[('200', '200'), ('404', '404'), ('301', '301'), ('401', '401')], max_length=10)),
                ('content_type', models.CharField(choices=[('application/json', 'application/json'), ('application/xml', 'application/xml'), ('text/json', 'text/json'), ('text/xml', 'text/xml'), ('raw', 'raw')], max_length=50)),
                ('response_body', models.TextField(max_length=5000)),
                ('response_delay', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AddField(
            model_name='api',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Project'),
        ),
    ]
